apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Crée un Load Balancer externe sur GCP
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80 # Port externe
    targetPort: 80 # Port du conteneur